# <center>Data Mining Project 1 Spring semester 2019-2020</center>
## <center>Παναγιώτης Ευαγγελίου &emsp; 1115201500039</center>
## <center>Γεώργιος Μαραγκοζάκης &emsp; 1115201500089</center>

___

### Do all the necessary imports for this notebook

In [1]:
# for data exploration
import pandas as pd
import os
from IPython.display import display

# for something else

## __Data Exploration__

- ### *Make one csv with the specific columns*

In [2]:
myMonthsFolder = ['febrouary','march','april']
dataPathDir = './data/'

allMonthDf = []

# for each month
for month in myMonthsFolder:
    print('Folder ' + month + ':')
    specificPath = dataPathDir + month + '/'

    # list of dataframes of this month
    monthFilesDfList = []

    # find the column's names of each csv
    for fileName in os.listdir(specificPath):
        # we need to check only .csv files
        if fileName.endswith(".csv"):
            thisCsv = pd.read_csv(os.path.join(specificPath, fileName), dtype='unicode')
            
            # make a list of columns of this file 
            columnsList = [x for x in thisCsv.columns]

            # make columns df for this file
            d = {fileName:columnsList}
            df = pd.DataFrame(data=d)
            
            # append this df to monthFilesDfList
            monthFilesDfList.append(df)
        else:
            continue

    concatDf = pd.concat(monthFilesDfList, axis=1)
    concatDf = concatDf.fillna('-')
    concatDf.name = month
    display(concatDf)

    allMonthDf.append(concatDf)

# check if corresponding files in months' folders have the same column names
allAreEqual = True
curentDf = allMonthDf[0]
for x in allMonthDf[1:]:
    if not curentDf.equals(x):
        allAreEqual = False
        break

if allAreEqual:
    print('Column names in corresponding files in months\' folders are the same.')
else:
    print('Column names in corresponding files in months\' folders are not the same.')

Folder febrouary:

,listings0.csv,neighbourhoods.csv,reviews0.csv,listings.csv,reviews.csv,calendar.csv
0,id,neighbourhood_group,listing_id,id,listing_id,listing_id
1,name,neighbourhood,date,listing_url,id,date
2,host_id,-,-,scrape_id,date,available
3,host_name,-,-,last_scraped,reviewer_id,price
4,neighbourhood_group,-,-,name,reviewer_name,adjusted_price
...,...,...,...,...,...,...
101,-,-,-,calculated_host_listings_count,-,-
102,-,-,-,calculated_host_listings_count_entire_homes,-,-
103,-,-,-,calculated_host_listings_count_private_rooms,-,-
104,-,-,-,calculated_host_listings_count_shared_rooms,-,-
105,-,-,-,reviews_per_month,-,-

Folder march:

,listings0.csv,neighbourhoods.csv,reviews0.csv,listings.csv,reviews.csv,calendar.csv
0,id,neighbourhood_group,listing_id,id,listing_id,listing_id
1,name,neighbourhood,date,listing_url,id,date
2,host_id,-,-,scrape_id,date,available
3,host_name,-,-,last_scraped,reviewer_id,price
4,neighbourhood_group,-,-,name,reviewer_name,adjusted_price
...,...,...,...,...,...,...
101,-,-,-,calculated_host_listings_count,-,-
102,-,-,-,calculated_host_listings_count_entire_homes,-,-
103,-,-,-,calculated_host_listings_count_private_rooms,-,-
104,-,-,-,calculated_host_listings_count_shared_rooms,-,-
105,-,-,-,reviews_per_month,-,-

Folder april:

,listings0.csv,neighbourhoods.csv,reviews0.csv,listings.csv,reviews.csv,calendar.csv
0,id,neighbourhood_group,listing_id,id,listing_id,listing_id
1,name,neighbourhood,date,listing_url,id,date
2,host_id,-,-,scrape_id,date,available
3,host_name,-,-,last_scraped,reviewer_id,price
4,neighbourhood_group,-,-,name,reviewer_name,adjusted_price
...,...,...,...,...,...,...
101,-,-,-,calculated_host_listings_count,-,-
102,-,-,-,calculated_host_listings_count_entire_homes,-,-
103,-,-,-,calculated_host_listings_count_private_rooms,-,-
104,-,-,-,calculated_host_listings_count_shared_rooms,-,-
105,-,-,-,reviews_per_month,-,-

Column names in corresponding files in months' folders are the same.

Παρατηρούμε ότι:
- Τα αντίστοιχα αρχεία σε όλους τους φακέλους των μηνών έχουν τα ίδια ονόματα στηλών
- Τα περισσότερα .csv αρχεία έχουν σχετικά λίγες στήλες εκτός από το αρχείο listings.csv το οποίο
έχει πολλές στήλες οπότε είναι δύσκολο να βρούμε "με το μάτι" τις στήλες που ζητούνται

__Let's find which file has each of the specific columns that we need. As column
names in corresponding files in months' folders are the same we just need to check only one folder.__